project_id = "fwtbdwffnfljtodueukt"

[functions.sync-steps]
verify_jwt = false

[functions.reset-daily-steps]
verify_jwt = false

[functions.send-notifications]
verify_jwt = false

[functions.get-user-emails]
verify_jwt = false

[functions.send-auth-email]
verify_jwt = false
